# This file was generated by GoReleaser. DO NOT EDIT.
cask "crawlsnap" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "9d40158ccb44b0089a185ca315474af0025e5d9e82925ef31ea8badaa63cddca"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "84599b7643616192e6b3ab86ca693b49c87b60a680ce9740bbcd97adc04b8377"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "547f67e0e6532339c2ce912ec1300a91447008a4cc30ee40ebc13b124248c9a3"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b467dad72192162ad3ba1ecc547e19133ad2af0fdef8723b99eeae14bf24b4d"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "crawlsnap"
  desc "Official CLI for the CrawlSnap data intelligence platform"
  homepage "https://crawlsnap.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crawlsnap"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crawlsnap"]
    end
  end

  # No zap stanza required

end
