# This file was generated by GoReleaser. DO NOT EDIT.
cask "crawlsnap" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "830f29f9697edd8a49592e7dfb7aa69400574baba7c4043bac339d8ba31dc6fd"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fd40d278a67a838b41f4f3e2583f06541c183745e5deba1c7c87a5fa162c2e6"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c0a53a6696949149a42f94891a64c7331e74d5579a06af33a6552c63ecc7501e"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "06891658b4a0233775856283ff3b63cd1dfc9832db9576552cc4ee74593fe4da"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "crawlsnap"
  desc "Official CLI for the CrawlSnap data intelligence platform"
  homepage "https://crawlsnap.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crawlsnap"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crawlsnap"]
    end
  end

  # No zap stanza required

end
