# This file was generated by GoReleaser. DO NOT EDIT.
cask "crawlsnap" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "608e7aedb4e272b883cb24052a7cc809c6ec7c03dff8fa5baedde7bacf24dcb1"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8572d18e1d2d999d9b9a51af150f7d350e41bf056280ae70e49ac4c13cf79ec"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6fa08a714514ddc9aeeae3f22776e3b327d308271446e3cba4b57d9d5de9bfe"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5dbd14a86af186d51f9e45716d4013d2c09a572d0f5496cb50ebe2e151863b72"
      url "https://github.com/crawlsnap/crawlsnap-cli/releases/download/v#{version}/crawlsnap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "crawlsnap"
  desc "Official CLI for the CrawlSnap data intelligence platform"
  homepage "https://crawlsnap.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crawlsnap"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crawlsnap"]
    end
  end

  # No zap stanza required

end
